[main]
name = "pwnagotchi"
lang = "en"
iface = "wlan1"
whitelist = [
    "EXAMPLE_NETWORK",
    "ANOTHER_EXAMPLE_NETWORK",
    "fo:od:ba:be:fo:od",
    "fo:od:ba"
]

[main.plugins.prova]
enabled=true

[main.plugins.auto-tune]
enabled = true


[personality]
advertise = true
deauth = true
associate = true
channels = []
min_rssi = -200
ap_ttl = 120
sta_ttl = 300
recon_time = 30
max_inactive_scale = 2
recon_inactive_multiplier = 2
hop_recon_time = 10
min_recon_time = 5
max_interactions = 3
max_misses_for_recon = 5
excited_num_epochs = 10
bored_num_epochs = 15
sad_num_epochs = 25
bond_encounters_factor = 20000
throttle_a = 0.4
throttle_d = 0.9

[bettercap]
handshakes = "/home/riccardo/riccardo/pwnisher/"
silence = [
    "session.started",
    "ble.device.new",
    "ble.device.lost",
    "ble.device.service.discovered",
    "ble.device.characteristic.discovered",
    "ble.device.disconnected",
    "ble.device.connected",
    "ble.connection.timeout",
    "wifi.client.new",
    "wifi.client.lost",
    "wifi.client.probe",
    "wifi.ap.new",
    "wifi.ap.lost",
    "mod.started"
]
